model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 256
  hidden_dims: [32, 64, 128, 256, 512, 1024]


data_params:
  data_path: "Data/Classification1"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 128
  num_workers: 4
  problem: "Winding_Head" #["Screw", "Sheet_Metal_Package", "Winding_Head"]

exp_params:
  LR: 0.005
  weight_decay: 0.0001
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  # gpus: [1]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
